Fix radarr to rescan and run rename commands
revenz/FileFlowsRepository pull request #29
Opened 2024-06-08 04:28 UTC by ant385525

## CLA

[X] I agree that by opening a pull requests I am handing over copyright ownership of my work contained in that pull request to the FileFlows project and the project owner. My contribution will become licensed under the same license as the overall project.

2024-06-08 23:49 UTC, revenz requested changes

2024-06-08 23:49 UTC, revenz commented on Scripts/Flow/Applications/Radarr/Radarr - Rename.js
> + * @revision 1
cant go down in revisions, also why change the authors name?

2024-06-09 00:19 UTC, ant385525 commented on Scripts/Flow/Applications/Radarr/Radarr - Rename.js
> + * @revision 1
It's completely rewritten, the other script didn't do anything so I was considering it a new script. Should the revision still go up? and I can add the other author's name back, I don't code much so dk the best practices

2024-06-09 03:08 UTC, revenz commented on Scripts/Flow/Applications/Radarr/Radarr - Rename.js
> + * @revision 1
the revision still needs to be higher so it actually gets updated.  the revision is how it determines if there is a newer version.

Have you spoken to the original author, are they happy with replacing this?

2024-06-09 03:14 UTC, ant385525 commented on Scripts/Flow/Applications/Radarr/Radarr - Rename.js
> + * @revision 1
I see ok. And yeah see the discord in channel scripts-code-functions. The other version wasn't functional

2024-06-09 03:26 UTC, merged