Feature/add new arr import scripts
revenz/FileFlowsRepository pull request #73
Opened 2024-12-18 06:58 UTC by BuSHari

A new and improved Arr scripts for Manual Import scripts

[X] I agree that by opening a pull requests I am handing over copyright ownership of my work contained in that pull request to the FileFlows project and the project owner. My contribution will become licensed under the same license as the overall project.

2024-12-18 21:47 UTC, revenz requested changes

2024-12-18 21:47 UTC, revenz commented on Scripts/Flow/Applications/Radarr/Radarr - Trigger Manual Import.js
> + * @param {bool} UseUnmappedPath Whether to Unmap the path to the original FileFlows Server path when using nodes in different platforms (e.g. Docker and Windows)
these comments are wrong, it only has 2 parameters, yet you have comments for more

2024-12-18 21:47 UTC, revenz commented on Scripts/Flow/Applications/Sonarr/Sonarr - Trigger Manual Import.js
> +function Script(URL, ApiKey) {
these comments are wrong too

2024-12-19 07:14 UTC, BuSHari commented on Scripts/Flow/Applications/Radarr/Radarr - Trigger Manual Import.js
> + * @param {bool} UseUnmappedPath Whether to Unmap the path to the original FileFlows Server path when using nodes in different platforms (e.g. Docker and Windows)
Fixed

2024-12-19 07:15 UTC, BuSHari commented on Scripts/Flow/Applications/Sonarr/Sonarr - Trigger Manual Import.js
> +function Script(URL, ApiKey) {
Fixed

2024-12-19 07:25 UTC, merged